import re
from fpdf import FPDF
from utils.helpers import sanitize_for_pdf

class StudyNotesPDF(FPDF):
    def __init__(self, title: str):
        super().__init__()
        self.doc_title = title
        
    def header(self):
        # Header banner
        self.set_font('helvetica', 'B', 8)
        self.set_text_color(100, 110, 120)
        self.cell(0, 6, "AI YouTube Transcript Summarizer | Study Notes", 0, 0, 'L')
        # Line break
        self.set_draw_color(220, 224, 230)
        self.set_line_width(0.2)
        self.line(10, 18, 200, 18)
        self.ln(10)
        
    def footer(self):
        # Footer position
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        # Horizontal line
        self.set_draw_color(240, 240, 240)
        self.line(10, 282, 200, 282)
        
        # Output title on footer left, page number on footer right
        # FPDF2 allows splitting content in cells
        self.cell(100, 10, f"Notes: {self.doc_title[:45]}...", 0, 0, 'L')
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", 0, 0, 'R')

def generate_markdown(content: str, title: str, video_url: str) -> str:
    """
    Formulates a clean markdown file template containing metadata.
    
    Args:
        content (str): The markdown body generated by the LLM.
        title (str): YouTube video title.
        video_url (str): Source URL.
        
    Returns:
        str: Styled markdown string.
    """
    md = f"""# Study Notes: {title}

- **Source Video**: [{video_url}]({video_url})
- **Application**: AI YouTube Transcript Summarizer
- **Format Style**: Study Notes

---

{content}
"""
    return md

def generate_pdf(content: str, title: str) -> bytes:
    """
    Parses structural markdown headings, blocks, and lists,
    and outputs a formatted PDF file using fpdf2.
    
    Args:
        content (str): Markdown text.
        title (str): Video title.
        
    Returns:
        bytes: Binary PDF buffer content.
    """
    sanitized_title = sanitize_for_pdf(title)
    sanitized_content = sanitize_for_pdf(content)
    
    pdf = StudyNotesPDF(sanitized_title)
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    
    # Render Video Title on cover/start page
    pdf.set_font('helvetica', 'B', 18)
    pdf.set_text_color(26, 54, 93)  # Rich Deep Blue
    pdf.multi_cell(0, 10, sanitized_title)
    pdf.ln(5)
    
    # Parse markdown line by line
    lines = sanitized_content.split('\n')
    
    in_list = False
    in_table = False
    in_quote = False
    
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        
        # Skip video title repeated in contents if matches
        if line.startswith("# ") and (sanitized_title.lower() in line.lower() or "video title" in line.lower()):
            i += 1
            continue
            
        # Heading 1
        if line.startswith("# "):
            pdf.ln(4)
            heading_text = line[2:].strip()
            pdf.set_font('helvetica', 'B', 16)
            pdf.set_text_color(26, 54, 93)
            pdf.multi_cell(0, 10, heading_text)
            pdf.ln(2)
            
        # Heading 2
        elif line.startswith("## "):
            pdf.ln(4)
            # Avoid orphans by forcing a new page if near the bottom (less than 40mm left)
            if pdf.get_y() > 240:
                pdf.add_page()
                
            heading_text = line[3:].strip()
            pdf.set_font('helvetica', 'B', 12)
            pdf.set_text_color(44, 82, 130)  # Subtle Blue
            pdf.multi_cell(0, 8, heading_text)
            # Underline heading
            curr_y = pdf.get_y()
            pdf.set_draw_color(44, 82, 130)
            pdf.set_line_width(0.4)
            pdf.line(10, curr_y, 100, curr_y)
            pdf.ln(3)
            
        # Heading 3
        elif line.startswith("### "):
            pdf.ln(3)
            heading_text = line[4:].strip()
            pdf.set_font('helvetica', 'B', 11)
            pdf.set_text_color(74, 85, 104)  # Slate Gray
            pdf.multi_cell(0, 6, heading_text)
            pdf.ln(1)
            
        # Quote Block
        elif line.startswith(">"):
            pdf.set_font('helvetica', 'I', 9)
            pdf.set_text_color(113, 128, 150)
            quote_text = line[1:].strip()
            
            # Draw quote border box
            x_start = pdf.get_x()
            y_start = pdf.get_y()
            
            # Print text indented
            pdf.set_x(x_start + 5)
            pdf.multi_cell(0, 5, f'"{quote_text}"')
            
            # Draw line on the left side of the quote
            y_end = pdf.get_y()
            pdf.set_draw_color(203, 213, 224)
            pdf.set_line_width(0.8)
            pdf.line(x_start + 2, y_start, x_start + 2, y_end)
            
            pdf.set_text_color(0, 0, 0) # Reset color
            pdf.ln(2)
            
        # Bullet Lists
        elif line.startswith("- ") or line.startswith("* "):
            pdf.set_font('helvetica', '', 9.5)
            pdf.set_text_color(45, 55, 72)
            bullet_text = line[2:].strip()
            
            # Replace markdown bold inside bullet **text** with standard text for simplicity
            bullet_text = re.sub(r'\*\*(.*?)\*\*', r'\1', bullet_text)
            
            # Render bullet points nicely
            pdf.set_x(15)
            # bullet character is code 149 in Symbol, but since we are standard Latin-1 we can use a hyphen or dot
            pdf.cell(5, 5, chr(149), 0, 0)
            pdf.set_x(20)
            pdf.multi_cell(0, 5, bullet_text)
            pdf.ln(1)
            
        # Table parsing
        elif line.startswith("|"):
            # Check if it is a separator line (e.g. |---|---|)
            if re.match(r'^\|[\s:-|]+$', line):
                i += 1
                continue
                
            pdf.set_font('helvetica', 'B' if "front" in line.lower() or "back" in line.lower() or "term" in line.lower() else '', 9)
            pdf.set_text_color(45, 55, 72)
            
            # Extract cell values
            cells = [c.strip() for c in line.split("|")[1:-1]]
            
            # Format and output as multi-column row
            col_width = 90  # two columns
            if len(cells) == 2:
                # Render flashcards or definitions nicely
                c1, c2 = cells[0], cells[1]
                c1_cleaned = re.sub(r'\*\*(.*?)\*\*', r'\1', c1)
                c2_cleaned = re.sub(r'\*\*(.*?)\*\*', r'\1', c2)
                
                # Check height of row
                c1_lines = pdf.get_string_width(c1_cleaned) / col_width
                c2_lines = pdf.get_string_width(c2_cleaned) / col_width
                row_height = max(1, int(max(c1_lines, c2_lines))) * 5 + 4
                
                # Draw cell borders
                curr_x = pdf.get_x()
                curr_y = pdf.get_y()
                
                # Draw border boxes
                pdf.rect(curr_x, curr_y, col_width, row_height)
                pdf.rect(curr_x + col_width, curr_y, col_width, row_height)
                
                # Print cell texts
                pdf.set_xy(curr_x + 2, curr_y + 2)
                pdf.multi_cell(col_width - 4, 4, c1_cleaned)
                
                pdf.set_xy(curr_x + col_width + 2, curr_y + 2)
                pdf.multi_cell(col_width - 4, 4, c2_cleaned)
                
                pdf.set_xy(curr_x, curr_y + row_height)
            else:
                # Fallback multi cell output
                combined = " | ".join(cells)
                pdf.multi_cell(0, 5, combined)
            
            pdf.ln(1)
            
        # Empty Line
        elif not line:
            pdf.ln(2)
            
        # Standard Paragraph
        else:
            pdf.set_font('helvetica', '', 9.5)
            pdf.set_text_color(45, 55, 72)
            
            # Clean markdown bold tags
            clean_line = re.sub(r'\*\*(.*?)\*\*', r'\1', line)
            
            # Clean markdown code blocks
            clean_line = re.sub(r'`(.*?)`', r'\1', clean_line)
            
            pdf.multi_cell(0, 5.5, clean_line)
            pdf.ln(1.5)
            
        i += 1
        
    return bytes(pdf.output())
